оформление
Anton-Pevitsyn/goit-markup-hw-02 pull request #1
Opened 2020-12-22 15:15 UTC by Anton-Pevitsyn

2020-12-23 16:16 UTC, magom001 requested changes

2020-12-23 16:16 UTC, magom001 commented on css/style.css
>  .site-nav a {
по условиям дз НЕ допускается использование тэгов в селекторах

2020-12-28 17:33 UTC, Anton-Pevitsyn commented on css/style.css
>  .site-nav a {
Внес исправления, исключил все селекторы тэгов в css.

2020-12-29 06:56 UTC, magom001 commented on css/style.css
>    color: #ffffff;
цвет в переменную унеси

2020-12-29 06:57 UTC, magom001 approved these changes

2020-12-30 15:29 UTC, merged